In [1]:
import pandas as pd
import numpy as np

In [2]:
df_dataco=pd.read_csv("../data/raw_data/DataCoSupplyChainDataset.csv",encoding="latin1")
df_token=pd.read_csv("../data/raw_data/tokenized_access_logs.csv")

# 1. DataCo Supply Chain Dataset

1. Basic Info

In [3]:
df_dataco.head()

,Type,Days for shipping (real),Days for shipment (scheduled),Benefit per order,Sales per customer,Delivery Status,Late_delivery_risk,Category Id,Category Name,Customer City,...,Order Zipcode,Product Card Id,Product Category Id,Product Description,Product Image,Product Name,Product Price,Product Status,shipping date (DateOrders),Shipping Mode
0,DEBIT,3,4,91.250000,314.640015,Advance shipping,0,73,Sporting Goods,Caguas,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,2/3/2018 22:56,Standard Class
1,TRANSFER,5,4,-249.089996,311.359985,Late delivery,1,73,Sporting Goods,Caguas,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/18/2018 12:27,Standard Class
2,CASH,4,4,-247.779999,309.720001,Shipping on time,0,73,Sporting Goods,San Jose,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/17/2018 12:06,Standard Class
3,DEBIT,3,4,22.860001,304.809998,Advance shipping,0,73,Sporting Goods,Los Angeles,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/16/2018 11:45,Standard Class
4,PAYMENT,2,4,134.210007,298.250000,Advance shipping,0,73,Sporting Goods,Caguas,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/15/2018 11:24,Standard Class

In [4]:
df_dataco.tail()

,Type,Days for shipping (real),Days for shipment (scheduled),Benefit per order,Sales per customer,Delivery Status,Late_delivery_risk,Category Id,Category Name,Customer City,...,Order Zipcode,Product Card Id,Product Category Id,Product Description,Product Image,Product Name,Product Price,Product Status,shipping date (DateOrders),Shipping Mode
180514,CASH,4,4,40.000000,399.980011,Shipping on time,0,45,Fishing,Brooklyn,...,NaN,1004,45,NaN,http://images.acmesports.sports/Field+%26+Stre...,Field & Stream Sportsman 16 Gun Fire Safe,399.980011,0,1/20/2016 3:40,Standard Class
180515,DEBIT,3,2,-613.770019,395.980011,Late delivery,1,45,Fishing,Bakersfield,...,NaN,1004,45,NaN,http://images.acmesports.sports/Field+%26+Stre...,Field & Stream Sportsman 16 Gun Fire Safe,399.980011,0,1/19/2016 1:34,Second Class
180516,TRANSFER,5,4,141.110001,391.980011,Late delivery,1,45,Fishing,Bristol,...,NaN,1004,45,NaN,http://images.acmesports.sports/Field+%26+Stre...,Field & Stream Sportsman 16 Gun Fire Safe,399.980011,0,1/20/2016 21:00,Standard Class
180517,PAYMENT,3,4,186.229996,387.980011,Advance shipping,0,45,Fishing,Caguas,...,NaN,1004,45,NaN,http://images.acmesports.sports/Field+%26+Stre...,Field & Stream Sportsman 16 Gun Fire Safe,399.980011,0,1/18/2016 20:18,Standard Class
180518,PAYMENT,4,4,168.949997,383.980011,Shipping on time,0,45,Fishing,Caguas,...,NaN,1004,45,NaN,http://images.acmesports.sports/Field+%26+Stre...,Field & Stream Sportsman 16 Gun Fire Safe,399.980011,0,1/19/2016 18:54,Standard Class

In [5]:
df_dataco.info()

<class 'pandas.DataFrame'>
RangeIndex: 180519 entries, 0 to 180518
Data columns (total 53 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   Type                           180519 non-null  str
 1   Days for shipping (real)       180519 non-null  int64
 2   Days for shipment (scheduled)  180519 non-null  int64
 3   Benefit per order              180519 non-null  float64
 4   Sales per customer             180519 non-null  float64
 5   Delivery Status                180519 non-null  str
 6   Late_delivery_risk             180519 non-null  int64
 7   Category Id                    180519 non-null  int64
 8   Category Name                  180519 non-null  str
 9   Customer City                  180519 non-null  str
 10  Customer Country               180519 non-null  str
 11  Customer Email                 180519 non-null  str
 12  Customer Fname                 180519 non-null  str
 13  Customer Id                    180519 non-null  int64
 14  Customer Lname                 180511 non-null  str
 15  Customer Password              180519 non-null  str
 16  Customer Segment               180519 non-null  str
 17  Customer State                 180519 non-null  str
 18  Customer Street                180519 non-null  str
 19  Customer Zipcode               180516 non-null  float64
 20  Department Id                  180519 non-null  int64
 21  Department Name                180519 non-null  str
 22  Latitude                       180519 non-null  float64
 23  Longitude                      180519 non-null  float64
 24  Market                         180519 non-null  str
 25  Order City                     180519 non-null  str
 26  Order Country                  180519 non-null  str
 27  Order Customer Id              180519 non-null  int64
 28  order date (DateOrders)        180519 non-null  str
 29  Order Id                       180519 non-null  int64
 30  Order Item Cardprod Id         180519 non-null  int64
 31  Order Item Discount            180519 non-null  float64
 32  Order Item Discount Rate       180519 non-null  float64
 33  Order Item Id                  180519 non-null  int64
 34  Order Item Product Price       180519 non-null  float64
 35  Order Item Profit Ratio        180519 non-null  float64
 36  Order Item Quantity            180519 non-null  int64
 37  Sales                          180519 non-null  float64
 38  Order Item Total               180519 non-null  float64
 39  Order Profit Per Order         180519 non-null  float64
 40  Order Region                   180519 non-null  str
 41  Order State                    180519 non-null  str
 42  Order Status                   180519 non-null  str
 43  Order Zipcode                  24840 non-null   float64
 44  Product Card Id                180519 non-null  int64
 45  Product Category Id            180519 non-null  int64
 46  Product Description            0 non-null       float64
 47  Product Image                  180519 non-null  str
 48  Product Name                   180519 non-null  str
 49  Product Price                  180519 non-null  float64
 50  Product Status                 180519 non-null  int64
 51  shipping date (DateOrders)     180519 non-null  str
 52  Shipping Mode                  180519 non-null  str
dtypes: float64(15), int64(14), str(24)
memory usage: 73.0 MB

In [6]:
df_dataco.shape

(180519, 53)

In [7]:
df_dataco.describe()

,Days for shipping (real),Days for shipment (scheduled),Benefit per order,Sales per customer,Late_delivery_risk,Category Id,Customer Id,Customer Zipcode,Department Id,Latitude,...,Order Item Quantity,Sales,Order Item Total,Order Profit Per Order,Order Zipcode,Product Card Id,Product Category Id,Product Description,Product Price,Product Status
count,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000,180516.000000,180519.000000,180519.000000,...,180519.000000,180519.000000,180519.000000,180519.000000,24840.000000,180519.000000,180519.000000,0.0,180519.000000,180519.0
mean,3.497654,2.931847,21.974989,183.107609,0.548291,31.851451,6691.379495,35921.126914,5.443460,29.719955,...,2.127638,203.772096,183.107609,21.974989,55426.132327,692.509764,31.851451,NaN,141.232550,0.0
std,1.623722,1.374449,104.433526,120.043670,0.497664,15.640064,4162.918106,37542.461122,1.629246,9.813646,...,1.453451,132.273077,120.043670,104.433526,31919.279101,336.446807,15.640064,NaN,139.732492,0.0
min,0.000000,0.000000,-4274.979980,7.490000,0.000000,2.000000,1.000000,603.000000,2.000000,-33.937553,...,1.000000,9.990000,7.490000,-4274.979980,1040.000000,19.000000,2.000000,NaN,9.990000,0.0
25%,2.000000,2.000000,7.000000,104.379997,0.000000,18.000000,3258.500000,725.000000,4.000000,18.265432,...,1.000000,119.980003,104.379997,7.000000,23464.000000,403.000000,18.000000,NaN,50.000000,0.0
50%,3.000000,4.000000,31.520000,163.990005,1.000000,29.000000,6457.000000,19380.000000,5.000000,33.144863,...,1.000000,199.919998,163.990005,31.520000,59405.000000,627.000000,29.000000,NaN,59.990002,0.0
75%,5.000000,4.000000,64.800003,247.399994,1.000000,45.000000,9779.000000,78207.000000,7.000000,39.279617,...,3.000000,299.950012,247.399994,64.800003,90008.000000,1004.000000,45.000000,NaN,199.990005,0.0
max,6.000000,4.000000,911.799988,1939.989990,1.000000,76.000000,20757.000000,99205.000000,12.000000,48.781933,...,5.000000,1999.989990,1939.989990,911.799988,99301.000000,1363.000000,76.000000,NaN,1999.989990,0.0

In [8]:
df_dataco.sample(5)

,Type,Days for shipping (real),Days for shipment (scheduled),Benefit per order,Sales per customer,Delivery Status,Late_delivery_risk,Category Id,Category Name,Customer City,...,Order Zipcode,Product Card Id,Product Category Id,Product Description,Product Image,Product Name,Product Price,Product Status,shipping date (DateOrders),Shipping Mode
20501,DEBIT,6,4,44.290001,391.980011,Late delivery,1,45,Fishing,Humacao,...,NaN,1004,45,NaN,http://images.acmesports.sports/Field+%26+Stre...,Field & Stream Sportsman 16 Gun Fire Safe,399.980011,0,1/19/2015 23:27,Standard Class
59266,PAYMENT,2,1,-4.730000,110.000000,Late delivery,1,26,Girls' Apparel,Caguas,...,NaN,567,26,NaN,http://images.acmesports.sports/adidas+Men%27s...,adidas Men's Germany Black Crest Away Tee,25.000000,0,4/14/2017 7:56,First Class
112261,TRANSFER,4,4,5.250000,46.480000,Shipping on time,0,46,Indoor/Outdoor Games,Bell Gardens,...,NaN,1014,46,NaN,http://images.acmesports.sports/O%27Brien+Men%...,O'Brien Men's Neoprene Life Vest,49.980000,0,11/19/2016 1:50,Standard Class
128737,DEBIT,3,4,132.289993,293.970001,Advance shipping,0,9,Cardio Equipment,Los Angeles,...,NaN,191,9,NaN,http://images.acmesports.sports/Nike+Men%27s+F...,Nike Men's Free 5.0+ Running Shoe,99.989998,0,3/13/2015 2:42,Standard Class
152706,PAYMENT,4,4,-463.859985,347.980011,Shipping on time,0,45,Fishing,Chesapeake,...,60076.0,1004,45,NaN,http://images.acmesports.sports/Field+%26+Stre...,Field & Stream Sportsman 16 Gun Fire Safe,399.980011,0,5/12/2016 8:35,Standard Class

In [9]:
df_dataco.columns

Index(['Type', 'Days for shipping (real)', 'Days for shipment (scheduled)',
       'Benefit per order', 'Sales per customer', 'Delivery Status',
       'Late_delivery_risk', 'Category Id', 'Category Name', 'Customer City',
       'Customer Country', 'Customer Email', 'Customer Fname', 'Customer Id',
       'Customer Lname', 'Customer Password', 'Customer Segment',
       'Customer State', 'Customer Street', 'Customer Zipcode',
       'Department Id', 'Department Name', 'Latitude', 'Longitude', 'Market',
       'Order City', 'Order Country', 'Order Customer Id',
       'order date (DateOrders)', 'Order Id', 'Order Item Cardprod Id',
       'Order Item Discount', 'Order Item Discount Rate', 'Order Item Id',
       'Order Item Product Price', 'Order Item Profit Ratio',
       'Order Item Quantity', 'Sales', 'Order Item Total',
       'Order Profit Per Order', 'Order Region', 'Order State', 'Order Status',
       'Order Zipcode', 'Product Card Id', 'Product Category Id',
       'Product Description', 'Product Image', 'Product Name', 'Product Price',
       'Product Status', 'shipping date (DateOrders)', 'Shipping Mode'],
      dtype='str')

2. Text Conversion

In [10]:
df_dataco.columns=df_dataco.columns.str.lower().str.strip().str.replace(" ","_")

3. Null Value Handling

In [11]:
df_dataco.isnull().mean()*100

type                               0.000000
days_for_shipping_(real)           0.000000
days_for_shipment_(scheduled)      0.000000
benefit_per_order                  0.000000
sales_per_customer                 0.000000
delivery_status                    0.000000
late_delivery_risk                 0.000000
category_id                        0.000000
category_name                      0.000000
customer_city                      0.000000
customer_country                   0.000000
customer_email                     0.000000
customer_fname                     0.000000
customer_id                        0.000000
customer_lname                     0.004432
customer_password                  0.000000
customer_segment                   0.000000
customer_state                     0.000000
customer_street                    0.000000
customer_zipcode                   0.001662
department_id                      0.000000
department_name                    0.000000
latitude                           0.000000
longitude                          0.000000
market                             0.000000
order_city                         0.000000
order_country                      0.000000
order_customer_id                  0.000000
order_date_(dateorders)            0.000000
order_id                           0.000000
order_item_cardprod_id             0.000000
order_item_discount                0.000000
order_item_discount_rate           0.000000
order_item_id                      0.000000
order_item_product_price           0.000000
order_item_profit_ratio            0.000000
order_item_quantity                0.000000
sales                              0.000000
order_item_total                   0.000000
order_profit_per_order             0.000000
order_region                       0.000000
order_state                        0.000000
order_status                       0.000000
order_zipcode                     86.239676
product_card_id                    0.000000
product_category_id                0.000000
product_description              100.000000
product_image                      0.000000
product_name                       0.000000
product_price                      0.000000
product_status                     0.000000
shipping_date_(dateorders)         0.000000
shipping_mode                      0.000000
dtype: float64

In [12]:
df_dataco["customer_lname"].mode()

0    Smith
Name: customer_lname, dtype: str

In [13]:
df_dataco["customer_lname"].dtypes

In [14]:
df_dataco["customer_lname"]=df_dataco["customer_lname"].fillna(df_dataco["customer_lname"].mode()[0])

In [15]:
df_dataco["customer_zipcode"].dtypes

dtype('float64')

In [16]:
df_dataco["customer_zipcode"].isnull().sum()

np.int64(3)

4. Duplicate Value Handling

In [17]:
df_dataco.duplicated().sum()

np.int64(0)

5. Data Type Fixing

In [18]:
df_dataco.dtypes

type                                 str
days_for_shipping_(real)           int64
days_for_shipment_(scheduled)      int64
benefit_per_order                float64
sales_per_customer               float64
delivery_status                      str
late_delivery_risk                 int64
category_id                        int64
category_name                        str
customer_city                        str
customer_country                     str
customer_email                       str
customer_fname                       str
customer_id                        int64
customer_lname                       str
customer_password                    str
customer_segment                     str
customer_state                       str
customer_street                      str
customer_zipcode                 float64
department_id                      int64
department_name                      str
latitude                         float64
longitude                        float64
market                               str
order_city                           str
order_country                        str
order_customer_id                  int64
order_date_(dateorders)              str
order_id                           int64
order_item_cardprod_id             int64
order_item_discount              float64
order_item_discount_rate         float64
order_item_id                      int64
order_item_product_price         float64
order_item_profit_ratio          float64
order_item_quantity                int64
sales                            float64
order_item_total                 float64
order_profit_per_order           float64
order_region                         str
order_state                          str
order_status                         str
order_zipcode                    float64
product_card_id                    int64
product_category_id                int64
product_description              float64
product_image                        str
product_name                         str
product_price                    float64
product_status                     int64
shipping_date_(dateorders)           str
shipping_mode                        str
dtype: object

In [19]:
# ORDER DATE
df_dataco["order_date_(dateorders)"].dtypes

In [20]:
df_dataco["order_date_(dateorders)"]=pd.to_datetime(df_dataco["order_date_(dateorders)"])

In [21]:
df_dataco["order_date_(dateorders)"]

0        2018-01-31 22:56:00
1        2018-01-13 12:27:00
2        2018-01-13 12:06:00
3        2018-01-13 11:45:00
4        2018-01-13 11:24:00
                 ...
180514   2016-01-16 03:40:00
180515   2016-01-16 01:34:00
180516   2016-01-15 21:00:00
180517   2016-01-15 20:18:00
180518   2016-01-15 18:54:00
Name: order_date_(dateorders), Length: 180519, dtype: datetime64[us]

In [22]:
df_dataco["order_year"]=df_dataco["order_date_(dateorders)"].dt.year

In [23]:
# shipping_date_(dateorders) 
df_dataco["shipping_date_(dateorders)"]=pd.to_datetime(df_dataco["shipping_date_(dateorders)"])

In [24]:
df_dataco["ship_year"]=df_dataco["shipping_date_(dateorders)"].dt.year

6. Value Consistency Check

In [25]:
df_dataco.columns.nunique()

55

In [26]:
df_dataco["customer_fname"].nunique()

782

In [27]:
df_dataco["customer_lname"].nunique()

1109

In [28]:
df_dataco["customer_country"].nunique()

2

In [29]:
df_dataco["customer_country"]

0         Puerto Rico
1         Puerto Rico
2             EE. UU.
3             EE. UU.
4         Puerto Rico
             ...
180514        EE. UU.
180515        EE. UU.
180516        EE. UU.
180517    Puerto Rico
180518    Puerto Rico
Name: customer_country, Length: 180519, dtype: str

In [30]:
df_dataco["customer_state"].nunique()

46

In [31]:
df_dataco["customer_state"]

0         PR
1         PR
2         CA
3         CA
4         PR
          ..
180514    NY
180515    CA
180516    CT
180517    PR
180518    PR
Name: customer_state, Length: 180519, dtype: str

7. Outliers Handling

In [34]:
# Calculate IQR
Q1 = df_dataco["delivery_delay"].quantile(0.25)
Q3 = df_dataco["delivery_delay"].quantile(0.75)
IQR = Q3 - Q1

# Define Outlier Range
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

# Extract Outliers
outliers = df_dataco[
    (df_dataco["delivery_delay"] < lower_bound) |
    (df_dataco["delivery_delay"] > upper_bound)
]

# View Results
outliers.shape
outliers.head()

,type,days_for_shipping_(real),days_for_shipment_(scheduled),benefit_per_order,sales_per_customer,delivery_status,late_delivery_risk,category_id,category_name,customer_city,...,product_description,product_image,product_name,product_price,product_status,shipping_date_(dateorders),shipping_mode,order_year,ship_year,delivery_delay
4,PAYMENT,2,4,134.210007,298.250000,Advance shipping,0,73,Sporting Goods,Caguas,...,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,2018-01-15 11:24:00,Standard Class,2018,2018,-2
10,TRANSFER,6,2,130.580002,272.029999,Shipping canceled,0,73,Sporting Goods,Caguas,...,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,2018-01-19 09:18:00,Second Class,2018,2018,4
11,TRANSFER,5,2,45.689999,268.760010,Late delivery,1,73,Sporting Goods,Freeport,...,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,2018-01-18 08:57:00,Second Class,2018,2018,3
16,PAYMENT,5,2,-246.360001,321.200012,Late delivery,1,73,Sporting Goods,Canovanas,...,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,2018-01-18 07:12:00,Second Class,2018,2018,3
25,DEBIT,6,2,131.169998,285.140015,Late delivery,1,73,Sporting Goods,Caguas,...,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,2018-01-19 04:03:00,Second Class,2018,2018,4

8. Feature Engineering

In [33]:
df_dataco["delivery_delay"]=df_dataco["days_for_shipping_(real)"]-df_dataco["days_for_shipment_(scheduled)"]

9. Filtering Data

In [35]:
df_dataco["customer_city"]

0              Caguas
1              Caguas
2            San Jose
3         Los Angeles
4              Caguas
             ...
180514       Brooklyn
180515    Bakersfield
180516        Bristol
180517         Caguas
180518         Caguas
Name: customer_city, Length: 180519, dtype: str

In [36]:
df_dataco[df_dataco["customer_city"]=="Los Angeles"]

,type,days_for_shipping_(real),days_for_shipment_(scheduled),benefit_per_order,sales_per_customer,delivery_status,late_delivery_risk,category_id,category_name,customer_city,...,product_description,product_image,product_name,product_price,product_status,shipping_date_(dateorders),shipping_mode,order_year,ship_year,delivery_delay
3,DEBIT,3,4,22.860001,304.809998,Advance shipping,0,73,Sporting Goods,Los Angeles,...,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.750000,0,2018-01-16 11:45:00,Standard Class,2018,2018,-1
196,TRANSFER,2,4,8.760000,99.580002,Shipping canceled,0,29,Shop By Sport,Los Angeles,...,NaN,http://images.acmesports.sports/Under+Armour+G...,Under Armour Girls' Toddler Spine Surge Runni,39.990002,0,2016-07-29 06:01:00,Standard Class,2016,2016,-2
314,DEBIT,5,4,-9.810000,166.199997,Late delivery,1,11,Fitness Accessories,Los Angeles,...,NaN,http://images.acmesports.sports/Under+Armour+H...,Under Armour Hustle Storm Medium Duffle Bag,34.990002,0,2015-10-08 15:33:00,Standard Class,2015,2015,1
349,TRANSFER,2,4,7.210000,65.580002,Advance shipping,0,26,Girls' Apparel,Los Angeles,...,NaN,http://images.acmesports.sports/TYR+Boys%27+Te...,TYR Boys' Team Digi Jammer,39.990002,0,2017-02-18 00:50:00,Standard Class,2017,2017,-2
353,TRANSFER,2,4,37.599998,80.000000,Advance shipping,0,24,Women's Apparel,Los Angeles,...,NaN,http://images.acmesports.sports/Nike+Men%27s+D...,Nike Men's Dri-FIT Victory Golf Polo,50.000000,0,2017-02-18 00:50:00,Standard Class,2017,2017,-2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
180157,TRANSFER,6,4,174.589996,387.980011,Late delivery,1,45,Fishing,Los Angeles,...,NaN,http://images.acmesports.sports/Field+%26+Stre...,Field & Stream Sportsman 16 Gun Fire Safe,399.980011,0,2016-02-11 16:36:00,Standard Class,2016,2016,2
180197,DEBIT,6,4,125.730003,371.980011,Late delivery,1,45,Fishing,Los Angeles,...,NaN,http://images.acmesports.sports/Field+%26+Stre...,Field & Stream Sportsman 16 Gun Fire Safe,399.980011,0,2016-02-09 12:03:00,Standard Class,2016,2016,2
180377,CASH,3,4,174.830002,371.980011,Advance shipping,0,45,Fishing,Los Angeles,...,NaN,http://images.acmesports.sports/Field+%26+Stre...,Field & Stream Sportsman 16 Gun Fire Safe,399.980011,0,2016-01-27 00:30:00,Standard Class,2016,2016,-1
180387,TRANSFER,5,4,143.990005,299.989990,Late delivery,1,45,Fishing,Los Angeles,...,NaN,http://images.acmesports.sports/Field+%26+Stre...,Field & Stream Sportsman 16 Gun Fire Safe,399.980011,0,2016-01-28 11:11:00,Standard Class,2016,2016,1
180448,DEBIT,2,4,162.529999,377.980011,Advance shipping,0,45,Fishing,Los Angeles,...,NaN,http://images.acmesports.sports/Field+%26+Stre...,Field & Stream Sportsman 16 Gun Fire Safe,399.980011,0,2016-01-22 03:19:00,Standard Class,2016,2016,-2

10. Import Clean Files

In [37]:
df_dataco.to_csv("../data/clean_data/datacocleaned.csv")

# 2. Tokonized Access Log Dataset

1. Basic Info

In [38]:
df_token.head()

,Product,Category,Date,Month,Hour,Department,ip,url
0,adidas Brazuca 2017 Official Match Ball,baseball & softball,9/1/2017 6:00,Sep,6,fitness,37.97.182.65,/department/fitness/category/baseball%20&%20so...
1,The North Face Women's Recon Backpack,hunting & shooting,9/1/2017 6:00,Sep,6,fan shop,206.56.112.1,/department/fan%20shop/category/hunting%20&%20...
2,adidas Kids' RG III Mid Football Cleat,featured shops,9/1/2017 6:00,Sep,6,apparel,215.143.180.0,/department/apparel/category/featured%20shops/...
3,Under Armour Men's Compression EV SL Slide,electronics,9/1/2017 6:00,Sep,6,footwear,206.56.112.1,/department/footwear/category/electronics/prod...
4,Pelican Sunstream 100 Kayak,water sports,9/1/2017 6:01,Sep,6,fan shop,136.108.56.242,/department/fan%20shop/category/water%20sports...

In [39]:
df_token.tail()

,Product,Category,Date,Month,Hour,Department,ip,url
469972,Nike Men's Free TR 5.0 TB Training Shoe,as seen on tv!,10/9/2017 21:21,Oct,21,footwear,93.166.57.36,/department/footwear/category/as%20seen%20on%2...
469973,Under Armour Hustle Storm Medium Duffle Bag,fitness accessories,10/9/2017 21:21,Oct,21,footwear,126.175.2.58,/department/footwear/category/fitness%20access...
469974,Under Armour Hustle Storm Medium Duffle Bag,fitness accessories,10/9/2017 21:22,Oct,21,footwear,201.210.19.242,/department/footwear/category/fitness%20access...
469975,Nike Men's Dri-FIT Victory Golf Polo,women's apparel,10/9/2017 21:22,Oct,21,golf,56.81.167.135,/department/golf/category/women's%20apparel/pr...
469976,Bridgestone e6 Straight Distance NFL San Dieg,electronics,10/9/2017 21:23,Oct,21,outdoors,146.184.239.226,/department/outdoors/category/electronics/prod...

In [40]:
df_token.shape

(469977, 8)

In [41]:
df_token.info()

<class 'pandas.DataFrame'>
RangeIndex: 469977 entries, 0 to 469976
Data columns (total 8 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   Product     469977 non-null  str
 1   Category    469977 non-null  str
 2   Date        469977 non-null  str
 3   Month       469977 non-null  str
 4   Hour        469977 non-null  int64
 5   Department  469977 non-null  str
 6   ip          469977 non-null  str
 7   url         469977 non-null  str
dtypes: int64(1), str(7)
memory usage: 28.7 MB

In [42]:
df_token.describe()

                Hour
count  469977.000000
mean       14.591827
std         5.574014
min         0.000000
25%        10.000000
50%        15.000000
75%        20.000000
max        23.000000

In [43]:
df_token.sample(4)

,Product,Category,Date,Month,Hour,Department,ip,url
300927,O'Brien Men's Neoprene Life Vest,indoor outdoor games,9/14/2017 22:57,Sep,22,fan shop,94.26.128.208,/department/fan%20shop/category/indoor/outdoor...
342337,Under Armour Kids' Mercenary Slide,electronics,1/10/2018 15:29,Jan,15,footwear,94.232.162.116,/department/footwear/category/electronics/prod...
294757,Under Armour Women's Micro G Skulpt Running S,boxing & mma,9/14/2017 22:39,Sep,22,footwear,33.68.172.162,/department/footwear/category/boxing%20&%20mma...
173597,Titleist Club Glove Travel Cover,golf gloves,11/8/2017 22:24,Nov,22,outdoors,62.119.226.57,/department/outdoors/category/golf%20gloves/pr...

In [44]:
df_token.columns

Index(['Product', 'Category', 'Date', 'Month', 'Hour', 'Department', 'ip',
       'url'],
      dtype='str')

2. Text Cleaning

In [45]:
df_token.columns=df_token.columns.str.strip().str.lower().str.replace(" ","_")

3. Null Value Handling

In [46]:
df_token.isnull().mean()*100

product       0.0
category      0.0
date          0.0
month         0.0
hour          0.0
department    0.0
ip            0.0
url           0.0
dtype: float64

4. Duplicate Value Handling

In [51]:
df_token.duplicated().sum()

np.int64(0)

In [52]:
df_token.duplicated().mean()*100

np.float64(0.0)

In [49]:
duplicates = df_token[df_token.duplicated(keep=False)]
duplicates.head()

,product,category,date,month,hour,department,ip,url
500,Perfect Fitness Perfect Rip Deck,cleats,9/1/2017 9:17,Sep,9,apparel,130.130.149.74,/department/apparel/category/cleats/product/Pe...
502,Perfect Fitness Perfect Rip Deck,cleats,9/1/2017 9:17,Sep,9,apparel,130.130.149.74,/department/apparel/category/cleats/product/Pe...
2292,adidas Men's Germany Black Crest Away Tee,girls' apparel,9/1/2017 20:46,Sep,20,golf,128.172.111.205,/department/golf/category/girls'%20apparel/pro...
2293,adidas Men's Germany Black Crest Away Tee,girls' apparel,9/1/2017 20:46,Sep,20,golf,128.172.111.205,/department/golf/category/girls'%20apparel/pro...
10089,adidas Kids' RG III Mid Football Cleat,featured shops,9/3/2017 9:19,Sep,9,apparel,168.185.213.44,/department/apparel/category/featured%20shops/...

In [50]:
df_token=df_token.drop_duplicates()

5. Value Consistency Check

In [57]:
df_token.columns.nunique()

8

6. Data Type Handling

In [63]:
df_token.dtypes

product         str
category        str
date            str
month           str
hour          int64
department      str
ip              str
url             str
dtype: object

In [64]:
df_token["date"]

0           9/1/2017 6:00
1           9/1/2017 6:00
2           9/1/2017 6:00
3           9/1/2017 6:00
4           9/1/2017 6:01
               ...
469972    10/9/2017 21:21
469973    10/9/2017 21:21
469974    10/9/2017 21:22
469975    10/9/2017 21:22
469976    10/9/2017 21:23
Name: date, Length: 466728, dtype: str

In [69]:
df_token["date"].dtype

dtype('<M8[us]')

In [68]:
df_token["date"]=pd.to_datetime(df_token["date"])

In [70]:
df_token["month"]

0         Sep
1         Sep
2         Sep
3         Sep
4         Sep
         ...
469972    Oct
469973    Oct
469974    Oct
469975    Oct
469976    Oct
Name: month, Length: 466728, dtype: str

In [71]:
df_token["hour"]

0          6
1          6
2          6
3          6
4          6
          ..
469972    21
469973    21
469974    21
469975    21
469976    21
Name: hour, Length: 466728, dtype: int64

In [ ]:
df_token["hour"]=pd.to

7. Filtering

In [78]:
df_token[df_token["month"] == "Sep"]["product"]

0               adidas Brazuca 2017 Official Match Ball
1                 The North Face Women's Recon Backpack
2                adidas Kids' RG III Mid Football Cleat
3            Under Armour Men's Compression EV SL Slide
4                           Pelican Sunstream 100 Kayak
                              ...
440202                      Pelican Sunstream 100 Kayak
440203    Under Armour Girls' Toddler Spine Surge Runni
440204          Nike Men's Fingertrap Max Training Shoe
440205          Columbia Men's PFG Anchor Tough T-Shirt
440206                              SOLE E35 Elliptical
Name: product, Length: 134348, dtype: str

8. Importing clean Files

In [79]:
df_token.to_csv("../data/clean_data/tokenizedLogo.csv")